export const quizQuestions = {
  "Interest in Outdoor vs. Indoor Work": [
    "I enjoy working outdoors and experiencing different weather conditions.",
    "I prefer indoor environments and controlled temperatures for work.",
    "I feel more productive when I'm working outside.",
    "I get easily bored working indoors all day.",
    "Being exposed to the elements doesn't bother me while working.",
  ],
  "Physical Strength and Endurance": [
    "I can easily lift heavy objects and perform physically demanding tasks.",
    "I enjoy jobs that require physical stamina and strength.",
    "I prefer working in jobs that keep me active and moving.",
    "I am comfortable standing for long periods of time.",
    "I have no problem with tasks that require bending, kneeling, or climbing.",
  ],
  "Mechanical Aptitude": [
    "I have a strong understanding of how machines and mechanical systems work.",
    "I enjoy working with tools and equipment to fix things.",
    "I can easily identify mechanical problems and troubleshoot them.",
    "I have a natural talent for assembling and disassembling complex devices.",
    "I am fascinated by how different mechanical systems function.",
  ],
  "Problem-solving Skills": [
    "I enjoy tackling complex problems and finding solutions.",
    "I am confident in my ability to analyze situations and identify the root cause of issues.",
    "I can think critically to devise effective strategies for problem-solving.",
    "I remain calm and focused when faced with difficult challenges.",
    "I enjoy learning from my mistakes and applying new approaches to problems.",
  ],
  "Attention to Detail": [
    "I take pride in the accuracy and precision of my work.",
    "I have a keen eye for spotting small errors or inconsistencies.",
    "I am thorough when completing tasks and always double-check my work.",
    "I believe that attention to detail is crucial for high-quality work.",
    "I can quickly notice if something is out of place or not done correctly.",
  ],
  "Creativity and Aesthetic Sense": [
    "I enjoy expressing myself creatively through my work.",
    "I have a strong sense of aesthetics and appreciate visually appealing designs.",
    "I can think outside the box and come up with innovative solutions.",
    "I enjoy working with colors, textures, and patterns to create visually pleasing results.",
    "I appreciate the artistic aspects of my job and always strive for creativity.",
  ],
  "Interpersonal and Communication Skills": [
    "I can easily communicate my thoughts and ideas to others.",
    "I enjoy working in teams and collaborating with colleagues.",
    "I am comfortable interacting with clients and customers.",
    "I can effectively manage conflicts and find common ground in disagreements.",
    "I am able to adapt my communication style to different situations and people.",
  ],
  "Technical Aptitude": [
    "I am comfortable learning and working with complex technical systems.",
    "I enjoy staying updated on the latest technological advancements in my field.",
    "I can quickly grasp new technical concepts and apply them to my work.",
    "I am skilled in using specialized software or equipment for my job.",
    "I am fascinated by how technology can improve work processes and results.",
  ],
  "Emotional Resilience": [
    "I can handle high-pressure situations without getting overwhelmed.",
    "I am able to adapt quickly to changing circumstances in my work environment.",
    "I can maintain my composure and focus when dealing with stress or setbacks.",
    "I am good at managing my emotions in challenging situations.",
    "I can bounce back quickly after facing disappointments or failures at work.",
  ],
  "Organizational and Time-management Skills": [
    "I am highly organized and can manage multiple tasks efficiently.",
    "I can prioritize tasks effectively and meet deadlines consistently.",
    "I have a structured approach to work and always plan my tasks in advance.",
    "I am able to juggle multiple responsibilities without compromising the quality of my work.",
    "I can easily adjust my schedule to accommodate unexpected changes or urgent tasks.",
  ],
};
