export const weights = {
  "I have a natural talent for assembling and disassembling complex devices.": {
    "Farm Manager": 2,
    "Conservation Tech": 2,
    "Animal Caretaker": 1,
    "Agricultural Inspector": 2,
    "Agricultural Operator": 2,
    "Greenhouse Manager": 2,
    "Pest Control": 2,
    "Landscape Architect": 2,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 3,
    "Electrical Power-Line": 3,
    "Wind Service": 4,
    "Commercial Diver": 3,
    "Recycling Coordinator": 2,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 2,
    Painter: 2,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 2,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 3,
    Plasterer: 2,
    Roofer: 2,
    "HVAC Tech": 4,
    "Crane Operator": 3,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 3,
    Welder: 4,
    "Chemical Plant": 4,
    Phlebotomist: 1,
    "Chemical Tech": 4,
    Paramedic: 2,
    "Licensed Nurse": 1,
    "Home Caretaker": 1,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 1,
    "Subway Operator": 2,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 2,
    "Cargo Agent": 2,
    "Food Service Manager": 1,
    "AV Technician": 3,
    "Video Editor": 2,
    Cook: 1,
    Hairdresser: 1,
    Manicurist: 1,
    "Auto Body": 3,
    "Appliance Repair": 4,
    Baker: 1,
  },
  "I am confident in my ability to analyze situations and identify the root cause of issues.":
    {
      "Farm Manager": 3,
      "Conservation Tech": 4,
      "Animal Caretaker": 2,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 3,
      "Pest Control": 4,
      "Landscape Architect": 4,
      Boilermaker: 3,
      "Solar Installer": 3,
      "Oil Operator": 3,
      "Electrical Power-Line": 4,
      "Wind Service": 3,
      "Commercial Diver": 4,
      "Recycling Coordinator": 4,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 3,
      "Highway Worker": 3,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 3,
      Carpenter: 4,
      "Cement Mason": 3,
      Paver: 3,
      Insulator: 3,
      Plasterer: 3,
      Roofer: 3,
      "HVAC Tech": 4,
      "Crane Operator": 3,
      "Bio Manufacturer": 4,
      "Metal Fabricator": 4,
      "Tool and Die Maker": 4,
      Machinist: 4,
      "Cabinet Maker": 4,
      Welder: 4,
      "Chemical Plant": 4,
      Phlebotomist: 3,
      "Chemical Tech": 4,
      Paramedic: 4,
      "Licensed Nurse": 3,
      "Home Caretaker": 3,
      "Nursing Assistant": 3,
      "Dental Assistant": 3,
      "Medical Admin": 4,
      "Dental Tech": 3,
      "Subway Operator": 3,
      "Machine Operator": 4,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 3,
      "Cargo Agent": 3,
      "Food Service Manager": 3,
      "AV Technician": 4,
      "Video Editor": 4,
      Cook: 2,
      Hairdresser: 2,
      Manicurist: 2,
      "Auto Body": 4,
      "Appliance Repair": 4,
      Baker: 2,
    },
  "I enjoy tackling complex problems and finding solutions.": {
    "Farm Manager": 3,
    "Conservation Tech": 4,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 3,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 3,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 5,
    Phlebotomist: 3,
    "Chemical Tech": 4,
    Paramedic: 4,
    "Licensed Nurse": 3,
    "Home Caretaker": 2,
    "Nursing Assistant": 2,
    "Dental Assistant": 2,
    "Medical Admin": 3,
    "Dental Tech": 2,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 3,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 2,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 2,
  },
  "I enjoy learning from my mistakes and applying new approaches to problems.":
    {
      "Farm Manager": 3,
      "Conservation Tech": 4,
      "Animal Caretaker": 2,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 3,
      "Pest Control": 4,
      "Landscape Architect": 4,
      Boilermaker: 4,
      "Solar Installer": 4,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 4,
      "Commercial Diver": 4,
      "Recycling Coordinator": 4,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 4,
      "Highway Worker": 3,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 4,
      Carpenter: 4,
      "Cement Mason": 4,
      Paver: 4,
      Insulator: 3,
      Plasterer: 3,
      Roofer: 3,
      "HVAC Tech": 4,
      "Crane Operator": 4,
      "Bio Manufacturer": 5,
      "Metal Fabricator": 5,
      "Tool and Die Maker": 5,
      Machinist: 5,
      "Cabinet Maker": 4,
      Welder: 4,
      "Chemical Plant": 5,
      Phlebotomist: 3,
      "Chemical Tech": 4,
      Paramedic: 4,
      "Licensed Nurse": 3,
      "Home Caretaker": 3,
      "Nursing Assistant": 3,
      "Dental Assistant": 3,
      "Medical Admin": 4,
      "Dental Tech": 3,
      "Subway Operator": 3,
      "Machine Operator": 4,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 3,
      "Cargo Agent": 3,
      "Food Service Manager": 3,
      "AV Technician": 4,
      "Video Editor": 4,
      Cook: 3,
      Hairdresser: 3,
      Manicurist: 3,
      "Auto Body": 4,
      "Appliance Repair": 4,
      Baker: 3,
    },
  "I enjoy working with tools and equipment to fix things.": {
    "Farm Manager": 3,
    "Conservation Tech": 3,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 2,
    Boilermaker: 5,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 3,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 5,
    Plumber: 5,
    "Sheet Metal": 5,
    "Highway Worker": 4,
    Painter: 4,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 4,
    Carpenter: 5,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 5,
    "Crane Operator": 4,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 5,
    Welder: 5,
    "Chemical Plant": 4,
    Phlebotomist: 3,
    "Chemical Tech": 3,
    Paramedic: 3,
    "Licensed Nurse": 2,
    "Home Caretaker": 2,
    "Nursing Assistant": 2,
    "Dental Assistant": 2,
    "Medical Admin": 2,
    "Dental Tech": 2,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 2,
    "AV Technician": 3,
    "Video Editor": 2,
    Cook: 3,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 5,
    "Appliance Repair": 5,
    Baker: 3,
  },
  "I remain calm and focused when faced with difficult challenges.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 3,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 5,
    "Recycling Coordinator": 3,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 4,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 5,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 4,
    Phlebotomist: 4,
    "Chemical Tech": 4,
    Paramedic: 5,
    "Licensed Nurse": 5,
    "Home Caretaker": 4,
    "Nursing Assistant": 5,
    "Dental Assistant": 4,
    "Medical Admin": 3,
    "Dental Tech": 4,
    "Subway Operator": 4,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 4,
    "Cargo Agent": 3,
    "Food Service Manager": 3,
    "AV Technician": 3,
    "Video Editor": 3,
    Cook: 4,
    Hairdresser: 4,
    Manicurist: 4,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 4,
  },
  "I take pride in the accuracy and precision of my work.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 5,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 3,
    Boilermaker: 5,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 5,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 4,
    Drywaller: 3,
    Electrician: 5,
    Plumber: 5,
    "Sheet Metal": 5,
    "Highway Worker": 4,
    Painter: 4,
    "Tile Setter": 5,
    "Flooring Installer": 4,
    "Brick Mason": 5,
    Carpenter: 5,
    "Cement Mason": 5,
    Paver: 5,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 5,
    "Crane Operator": 4,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 5,
    Welder: 5,
    "Chemical Plant": 5,
    Phlebotomist: 5,
    "Chemical Tech": 5,
    Paramedic: 4,
    "Licensed Nurse": 4,
    "Home Caretaker": 3,
    "Nursing Assistant": 4,
    "Dental Assistant": 5,
    "Medical Admin": 3,
    "Dental Tech": 5,
    "Subway Operator": 3,
    "Machine Operator": 5,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 3,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 4,
    Hairdresser: 4,
    Manicurist: 4,
    "Auto Body": 5,
    "Appliance Repair": 5,
    Baker: 4,
  },
  "I am good at managing my emotions in challenging situations.": {
    "Farm Manager": 3,
    "Conservation Tech": 3,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 2,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 2,
    Boilermaker: 3,
    "Solar Installer": 3,
    "Oil Operator": 3,
    "Electrical Power-Line": 3,
    "Wind Service": 3,
    "Commercial Diver": 4,
    "Recycling Coordinator": 2,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 3,
    Plumber: 3,
    "Sheet Metal": 3,
    "Highway Worker": 3,
    Painter: 2,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 3,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 2,
    Plasterer: 2,
    Roofer: 2,
    "HVAC Tech": 3,
    "Crane Operator": 4,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 3,
    "Tool and Die Maker": 3,
    Machinist: 3,
    "Cabinet Maker": 3,
    Welder: 3,
    "Chemical Plant": 3,
    Phlebotomist: 4,
    "Chemical Tech": 3,
    Paramedic: 5,
    "Licensed Nurse": 5,
    "Home Caretaker": 3,
    "Nursing Assistant": 4,
    "Dental Assistant": 3,
    "Medical Admin": 2,
    "Dental Tech": 3,
    "Subway Operator": 3,
    "Machine Operator": 3,
    "Aircraft Maintenance": 3,
    "Automotive Mechanic": 3,
    "Equipment Mechanic": 3,
    "Bike Mechanic": 2,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 2,
    "AV Technician": 2,
    "Video Editor": 2,
    Cook: 3,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 3,
  },
  "I am fascinated by how technology can improve work processes and results.": {
    "Farm Manager": 3,
    "Conservation Tech": 4,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 3,
    "Solar Installer": 5,
    "Oil Operator": 3,
    "Electrical Power-Line": 4,
    "Wind Service": 5,
    "Commercial Diver": 3,
    "Recycling Coordinator": 4,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 4,
    Plumber: 3,
    "Sheet Metal": 3,
    "Highway Worker": 2,
    Painter: 2,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 2,
    Carpenter: 3,
    "Cement Mason": 2,
    Paver: 2,
    Insulator: 3,
    Plasterer: 2,
    Roofer: 2,
    "HVAC Tech": 4,
    "Crane Operator": 3,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 3,
    Welder: 3,
    "Chemical Plant": 5,
    Phlebotomist: 3,
    "Chemical Tech": 5,
    Paramedic: 3,
    "Licensed Nurse": 3,
    "Home Caretaker": 2,
    "Nursing Assistant": 2,
    "Dental Assistant": 3,
    "Medical Admin": 3,
    "Dental Tech": 3,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 2,
    "Cargo Agent": 3,
    "Food Service Manager": 3,
    "AV Technician": 5,
    "Video Editor": 5,
    Cook: 3,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 3,
  },
  "I can prioritize tasks effectively and meet deadlines consistently.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 4,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 3,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 4,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 4,
    Phlebotomist: 4,
    "Chemical Tech": 4,
    Paramedic: 5,
    "Licensed Nurse": 5,
    "Home Caretaker": 3,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 4,
    "Dental Tech": 4,
    "Subway Operator": 4,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 4,
    "Cargo Agent": 3,
    "Food Service Manager": 5,
    "AV Technician": 3,
    "Video Editor": 3,
    Cook: 4,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 4,
  },
  "I can easily identify mechanical problems and troubleshoot them.": {
    "Farm Manager": 3,
    "Conservation Tech": 3,
    "Animal Caretaker": 1,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 3,
    "Pest Control": 2,
    "Landscape Architect": 2,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 3,
    "Wind Service": 4,
    "Commercial Diver": 3,
    "Recycling Coordinator": 2,
    "Carpet Installer": 1,
    Drywaller: 1,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 2,
    Painter: 1,
    "Tile Setter": 1,
    "Flooring Installer": 1,
    "Brick Mason": 1,
    Carpenter: 3,
    "Cement Mason": 1,
    Paver: 1,
    Insulator: 3,
    Plasterer: 1,
    Roofer: 1,
    "HVAC Tech": 5,
    "Crane Operator": 3,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 3,
    Phlebotomist: 1,
    "Chemical Tech": 3,
    Paramedic: 2,
    "Licensed Nurse": 1,
    "Home Caretaker": 1,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 1,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 1,
    "AV Technician": 3,
    "Video Editor": 1,
    Cook: 1,
    Hairdresser: 1,
    Manicurist: 1,
    "Auto Body": 4,
    "Appliance Repair": 5,
    Baker: 1,
  },
  "I have a structured approach to work and always plan my tasks in advance.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 4,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 3,
    "Recycling Coordinator": 4,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 4,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 4,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 4,
    Phlebotomist: 3,
    "Chemical Tech": 4,
    Paramedic: 4,
    "Licensed Nurse": 4,
    "Home Caretaker": 3,
    "Nursing Assistant": 3,
    "Dental Assistant": 3,
    "Medical Admin": 4,
    "Dental Tech": 3,
    "Subway Operator": 4,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 4,
    "Cargo Agent": 4,
    "Food Service Manager": 4,
    "AV Technician": 3,
    "Video Editor": 3,
    Cook: 3,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 3,
  },
  "I can bounce back quickly after facing disappointments or failures at work.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 4,
      "Animal Caretaker": 3,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 4,
      "Greenhouse Manager": 4,
      "Pest Control": 3,
      "Landscape Architect": 3,
      Boilermaker: 4,
      "Solar Installer": 4,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 4,
      "Commercial Diver": 4,
      "Recycling Coordinator": 4,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 4,
      "Highway Worker": 4,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 3,
      Carpenter: 4,
      "Cement Mason": 3,
      Paver: 3,
      Insulator: 3,
      Plasterer: 3,
      Roofer: 3,
      "HVAC Tech": 4,
      "Crane Operator": 4,
      "Bio Manufacturer": 4,
      "Metal Fabricator": 4,
      "Tool and Die Maker": 4,
      Machinist: 4,
      "Cabinet Maker": 4,
      Welder: 4,
      "Chemical Plant": 4,
      Phlebotomist: 3,
      "Chemical Tech": 4,
      Paramedic: 5,
      "Licensed Nurse": 4,
      "Home Caretaker": 3,
      "Nursing Assistant": 3,
      "Dental Assistant": 3,
      "Medical Admin": 3,
      "Dental Tech": 3,
      "Subway Operator": 4,
      "Machine Operator": 4,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 4,
      "Cargo Agent": 4,
      "Food Service Manager": 4,
      "AV Technician": 3,
      "Video Editor": 3,
      Cook: 3,
      Hairdresser: 3,
      Manicurist: 3,
      "Auto Body": 3,
      "Appliance Repair": 3,
      Baker: 3,
    },
  "I am able to adapt quickly to changing circumstances in my work environment.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 4,
      "Animal Caretaker": 3,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 4,
      "Greenhouse Manager": 4,
      "Pest Control": 3,
      "Landscape Architect": 3,
      Boilermaker: 4,
      "Solar Installer": 4,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 4,
      "Commercial Diver": 4,
      "Recycling Coordinator": 4,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 4,
      "Highway Worker": 4,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 3,
      Carpenter: 4,
      "Cement Mason": 3,
      Paver: 3,
      Insulator: 3,
      Plasterer: 3,
      Roofer: 3,
      "HVAC Tech": 4,
      "Crane Operator": 4,
      "Bio Manufacturer": 4,
      "Metal Fabricator": 4,
      "Tool and Die Maker": 4,
      Machinist: 4,
      "Cabinet Maker": 4,
      Welder: 4,
      "Chemical Plant": 4,
      Phlebotomist: 3,
      "Chemical Tech": 4,
      Paramedic: 5,
      "Licensed Nurse": 4,
      "Home Caretaker": 2,
      "Nursing Assistant": 3,
      "Dental Assistant": 3,
      "Medical Admin": 3,
      "Dental Tech": 3,
      "Subway Operator": 4,
      "Machine Operator": 4,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 4,
      "Cargo Agent": 4,
      "Food Service Manager": 3,
      "AV Technician": 3,
      "Video Editor": 3,
      Cook: 3,
      Hairdresser: 2,
      Manicurist: 2,
      "Auto Body": 3,
      "Appliance Repair": 3,
      Baker: 3,
    },
  "I enjoy working outdoors and experiencing different weather conditions.": {
    "Farm Manager": 5,
    "Conservation Tech": 5,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 5,
    "Greenhouse Manager": 2,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 3,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 1,
    "Recycling Coordinator": 3,
    "Carpet Installer": 1,
    Drywaller: 1,
    Electrician: 2,
    Plumber: 2,
    "Sheet Metal": 2,
    "Highway Worker": 5,
    Painter: 2,
    "Tile Setter": 1,
    "Flooring Installer": 1,
    "Brick Mason": 3,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 2,
    Plasterer: 1,
    Roofer: 4,
    "HVAC Tech": 2,
    "Crane Operator": 3,
    "Bio Manufacturer": 1,
    "Metal Fabricator": 1,
    "Tool and Die Maker": 1,
    Machinist: 1,
    "Cabinet Maker": 1,
    Welder: 2,
    "Chemical Plant": 1,
    Phlebotomist: 1,
    "Chemical Tech": 1,
    Paramedic: 4,
    "Licensed Nurse": 1,
    "Home Caretaker": 1,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 1,
    "Subway Operator": 1,
    "Machine Operator": 1,
    "Aircraft Maintenance": 2,
    "Automotive Mechanic": 2,
    "Equipment Mechanic": 2,
    "Bike Mechanic": 2,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 1,
    "AV Technician": 1,
    "Video Editor": 1,
    Cook: 1,
    Hairdresser: 1,
    Manicurist: 1,
    "Auto Body": 2,
    "Appliance Repair": 2,
    Baker: 1,
  },
  "I feel more productive when I'm working outside.": {
    "Farm Manager": 5,
    "Conservation Tech": 5,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 5,
    "Greenhouse Manager": 3,
    "Pest Control": 4,
    "Landscape Architect": 5,
    Boilermaker: 3,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 1,
    "Recycling Coordinator": 3,
    "Carpet Installer": 1,
    Drywaller: 1,
    Electrician: 2,
    Plumber: 2,
    "Sheet Metal": 2,
    "Highway Worker": 5,
    Painter: 2,
    "Tile Setter": 1,
    "Flooring Installer": 1,
    "Brick Mason": 3,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 2,
    Plasterer: 1,
    Roofer: 4,
    "HVAC Tech": 2,
    "Crane Operator": 3,
    "Bio Manufacturer": 1,
    "Metal Fabricator": 1,
    "Tool and Die Maker": 1,
    Machinist: 1,
    "Cabinet Maker": 1,
    Welder: 2,
    "Chemical Plant": 1,
    Phlebotomist: 1,
    "Chemical Tech": 1,
    Paramedic: 4,
    "Licensed Nurse": 1,
    "Home Caretaker": 1,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 1,
    "Subway Operator": 1,
    "Machine Operator": 1,
    "Aircraft Maintenance": 2,
    "Automotive Mechanic": 2,
    "Equipment Mechanic": 2,
    "Bike Mechanic": 2,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 1,
    "AV Technician": 1,
    "Video Editor": 1,
    Cook: 1,
    Hairdresser: 1,
    Manicurist: 1,
    "Auto Body": 2,
    "Appliance Repair": 2,
    Baker: 1,
  },
  "I believe that attention to detail is crucial for high-quality work.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 5,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 5,
    Boilermaker: 5,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 5,
    "Wind Service": 4,
    "Commercial Diver": 3,
    "Recycling Coordinator": 4,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 5,
    Plumber: 5,
    "Sheet Metal": 5,
    "Highway Worker": 3,
    Painter: 5,
    "Tile Setter": 5,
    "Flooring Installer": 4,
    "Brick Mason": 5,
    Carpenter: 5,
    "Cement Mason": 5,
    Paver: 4,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 5,
    "Crane Operator": 4,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 5,
    Welder: 5,
    "Chemical Plant": 4,
    Phlebotomist: 5,
    "Chemical Tech": 5,
    Paramedic: 5,
    "Licensed Nurse": 5,
    "Home Caretaker": 4,
    "Nursing Assistant": 5,
    "Dental Assistant": 5,
    "Medical Admin": 3,
    "Dental Tech": 5,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 4,
    "AV Technician": 4,
    "Video Editor": 5,
    Cook: 5,
    Hairdresser: 5,
    Manicurist: 5,
    "Auto Body": 5,
    "Appliance Repair": 5,
    Baker: 5,
  },
  "I can quickly grasp new technical concepts and apply them to my work.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 5,
    "Solar Installer": 5,
    "Oil Operator": 4,
    "Electrical Power-Line": 5,
    "Wind Service": 5,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 5,
    Plumber: 5,
    "Sheet Metal": 5,
    "Highway Worker": 3,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 4,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 4,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 5,
    "Crane Operator": 4,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 4,
    Welder: 5,
    "Chemical Plant": 5,
    Phlebotomist: 4,
    "Chemical Tech": 5,
    Paramedic: 4,
    "Licensed Nurse": 4,
    "Home Caretaker": 3,
    "Nursing Assistant": 3,
    "Dental Assistant": 4,
    "Medical Admin": 3,
    "Dental Tech": 4,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 3,
    "AV Technician": 5,
    "Video Editor": 5,
    Cook: 3,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 3,
  },
  "I have a keen eye for spotting small errors or inconsistencies.": {
    "Farm Manager": 3,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 5,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 5,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 5,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 5,
    Plumber: 5,
    "Sheet Metal": 5,
    "Highway Worker": 3,
    Painter: 5,
    "Tile Setter": 5,
    "Flooring Installer": 4,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 5,
    "Crane Operator": 4,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 5,
    Welder: 5,
    "Chemical Plant": 5,
    Phlebotomist: 5,
    "Chemical Tech": 5,
    Paramedic: 5,
    "Licensed Nurse": 5,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 5,
    "Medical Admin": 4,
    "Dental Tech": 5,
    "Subway Operator": 4,
    "Machine Operator": 4,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 4,
    "AV Technician": 5,
    "Video Editor": 5,
    Cook: 4,
    Hairdresser: 5,
    Manicurist: 5,
    "Auto Body": 5,
    "Appliance Repair": 5,
    Baker: 4,
  },
  "I get easily bored working indoors all day.": {
    "Farm Manager": 5,
    "Conservation Tech": 5,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 5,
    "Greenhouse Manager": 3,
    "Pest Control": 4,
    "Landscape Architect": 5,
    Boilermaker: 3,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 5,
    "Wind Service": 5,
    "Commercial Diver": 5,
    "Recycling Coordinator": 4,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 3,
    Plumber: 3,
    "Sheet Metal": 2,
    "Highway Worker": 5,
    Painter: 2,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 2,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 2,
    Plasterer: 2,
    Roofer: 4,
    "HVAC Tech": 2,
    "Crane Operator": 4,
    "Bio Manufacturer": 1,
    "Metal Fabricator": 2,
    "Tool and Die Maker": 1,
    Machinist: 1,
    "Cabinet Maker": 2,
    Welder: 2,
    "Chemical Plant": 1,
    Phlebotomist: 1,
    "Chemical Tech": 2,
    Paramedic: 4,
    "Licensed Nurse": 1,
    "Home Caretaker": 3,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 1,
    "Subway Operator": 2,
    "Machine Operator": 1,
    "Aircraft Maintenance": 2,
    "Automotive Mechanic": 2,
    "Equipment Mechanic": 2,
    "Bike Mechanic": 3,
    "Truck Driver": 3,
    "Cargo Agent": 1,
    "Food Service Manager": 2,
    "AV Technician": 1,
    "Video Editor": 1,
    Cook: 1,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 2,
    "Appliance Repair": 2,
    Baker: 1,
  },
  "I can maintain my composure and focus when dealing with stress or setbacks.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 4,
      "Animal Caretaker": 4,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 4,
      "Greenhouse Manager": 4,
      "Pest Control": 4,
      "Landscape Architect": 4,
      Boilermaker: 4,
      "Solar Installer": 4,
      "Oil Operator": 5,
      "Electrical Power-Line": 5,
      "Wind Service": 4,
      "Commercial Diver": 5,
      "Recycling Coordinator": 3,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 4,
      "Highway Worker": 4,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 3,
      Carpenter: 4,
      "Cement Mason": 4,
      Paver: 4,
      Insulator: 4,
      Plasterer: 3,
      Roofer: 4,
      "HVAC Tech": 4,
      "Crane Operator": 5,
      "Bio Manufacturer": 4,
      "Metal Fabricator": 4,
      "Tool and Die Maker": 4,
      Machinist: 4,
      "Cabinet Maker": 4,
      Welder: 4,
      "Chemical Plant": 4,
      Phlebotomist: 5,
      "Chemical Tech": 4,
      Paramedic: 5,
      "Licensed Nurse": 5,
      "Home Caretaker": 4,
      "Nursing Assistant": 4,
      "Dental Assistant": 4,
      "Medical Admin": 3,
      "Dental Tech": 4,
      "Subway Operator": 5,
      "Machine Operator": 4,
      "Aircraft Maintenance": 5,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 5,
      "Cargo Agent": 3,
      "Food Service Manager": 4,
      "AV Technician": 3,
      "Video Editor": 3,
      Cook: 3,
      Hairdresser: 3,
      Manicurist: 3,
      "Auto Body": 4,
      "Appliance Repair": 4,
      Baker: 3,
    },
  "I am highly organized and can manage multiple tasks efficiently.": {
    "Farm Manager": 5,
    "Conservation Tech": 4,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 5,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 5,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 3,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 5,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 3,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 5,
    Phlebotomist: 4,
    "Chemical Tech": 4,
    Paramedic: 5,
    "Licensed Nurse": 5,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 5,
    "Dental Tech": 4,
    "Subway Operator": 4,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 4,
    "Cargo Agent": 5,
    "Food Service Manager": 5,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 4,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 4,
  },
  "I can handle high-pressure situations without getting overwhelmed.": {
    "Farm Manager": 4,
    "Conservation Tech": 3,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 3,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 5,
    "Electrical Power-Line": 5,
    "Wind Service": 4,
    "Commercial Diver": 5,
    "Recycling Coordinator": 3,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 4,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 5,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 3,
    Welder: 4,
    "Chemical Plant": 5,
    Phlebotomist: 5,
    "Chemical Tech": 4,
    Paramedic: 5,
    "Licensed Nurse": 5,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 3,
    "Dental Tech": 3,
    "Subway Operator": 5,
    "Machine Operator": 4,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 2,
    "Truck Driver": 5,
    "Cargo Agent": 3,
    "Food Service Manager": 4,
    "AV Technician": 3,
    "Video Editor": 3,
    Cook: 3,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 3,
  },
  "I enjoy jobs that require physical stamina and strength.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 3,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 5,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 5,
    "Recycling Coordinator": 3,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 3,
    Plumber: 4,
    "Sheet Metal": 5,
    "Highway Worker": 5,
    Painter: 3,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 5,
    Carpenter: 4,
    "Cement Mason": 5,
    Paver: 5,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 5,
    "HVAC Tech": 4,
    "Crane Operator": 5,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 3,
    Machinist: 3,
    "Cabinet Maker": 4,
    Welder: 5,
    "Chemical Plant": 3,
    Phlebotomist: 2,
    "Chemical Tech": 3,
    Paramedic: 4,
    "Licensed Nurse": 2,
    "Home Caretaker": 3,
    "Nursing Assistant": 3,
    "Dental Assistant": 2,
    "Medical Admin": 1,
    "Dental Tech": 2,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 2,
    "AV Technician": 2,
    "Video Editor": 1,
    Cook: 3,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 3,
  },
  "I am fascinated by how different mechanical systems function.": {
    "Farm Manager": 3,
    "Conservation Tech": 3,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 3,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 3,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 3,
    Painter: 2,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 3,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 3,
    Plasterer: 2,
    Roofer: 2,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 3,
    Welder: 4,
    "Chemical Plant": 4,
    Phlebotomist: 1,
    "Chemical Tech": 3,
    Paramedic: 2,
    "Licensed Nurse": 1,
    "Home Caretaker": 1,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 1,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 1,
    "AV Technician": 3,
    "Video Editor": 2,
    Cook: 1,
    Hairdresser: 1,
    Manicurist: 1,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 1,
  },
  "Being exposed to the elements doesn't bother me while working.": {
    "Farm Manager": 5,
    "Conservation Tech": 5,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 5,
    "Greenhouse Manager": 3,
    "Pest Control": 4,
    "Landscape Architect": 5,
    Boilermaker: 3,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 5,
    "Recycling Coordinator": 3,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 2,
    Plumber: 2,
    "Sheet Metal": 3,
    "Highway Worker": 5,
    Painter: 3,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 3,
    Carpenter: 3,
    "Cement Mason": 3,
    Paver: 4,
    Insulator: 2,
    Plasterer: 2,
    Roofer: 4,
    "HVAC Tech": 2,
    "Crane Operator": 3,
    "Bio Manufacturer": 1,
    "Metal Fabricator": 2,
    "Tool and Die Maker": 1,
    Machinist: 1,
    "Cabinet Maker": 2,
    Welder: 2,
    "Chemical Plant": 1,
    Phlebotomist: 1,
    "Chemical Tech": 1,
    Paramedic: 3,
    "Licensed Nurse": 1,
    "Home Caretaker": 2,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 1,
    "Subway Operator": 1,
    "Machine Operator": 2,
    "Aircraft Maintenance": 2,
    "Automotive Mechanic": 2,
    "Equipment Mechanic": 2,
    "Bike Mechanic": 2,
    "Truck Driver": 2,
    "Cargo Agent": 1,
    "Food Service Manager": 1,
    "AV Technician": 1,
    "Video Editor": 1,
    Cook: 2,
    Hairdresser: 1,
    Manicurist: 1,
    "Auto Body": 2,
    "Appliance Repair": 2,
    Baker: 1,
  },
  "I am skilled in using specialized software or equipment for my job.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 4,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 5,
    "Solar Installer": 5,
    "Oil Operator": 5,
    "Electrical Power-Line": 5,
    "Wind Service": 5,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 5,
    Plumber: 5,
    "Sheet Metal": 5,
    "Highway Worker": 4,
    Painter: 3,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 3,
    Roofer: 4,
    "HVAC Tech": 5,
    "Crane Operator": 5,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 4,
    Welder: 5,
    "Chemical Plant": 5,
    Phlebotomist: 3,
    "Chemical Tech": 4,
    Paramedic: 4,
    "Licensed Nurse": 3,
    "Home Caretaker": 2,
    "Nursing Assistant": 2,
    "Dental Assistant": 3,
    "Medical Admin": 2,
    "Dental Tech": 3,
    "Subway Operator": 4,
    "Machine Operator": 5,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 4,
    "Truck Driver": 4,
    "Cargo Agent": 3,
    "Food Service Manager": 2,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 2,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 4,
    "Appliance Repair": 5,
    Baker: 2,
  },
  "I prefer indoor environments and controlled temperatures for work.": {
    "Farm Manager": 1,
    "Conservation Tech": 2,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 2,
    "Agricultural Operator": 1,
    "Greenhouse Manager": 4,
    "Pest Control": 2,
    "Landscape Architect": 2,
    Boilermaker: 4,
    "Solar Installer": 2,
    "Oil Operator": 2,
    "Electrical Power-Line": 2,
    "Wind Service": 2,
    "Commercial Diver": 2,
    "Recycling Coordinator": 3,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 1,
    Painter: 4,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 2,
    Carpenter: 3,
    "Cement Mason": 2,
    Paver: 2,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 1,
    "HVAC Tech": 4,
    "Crane Operator": 2,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 3,
    "Chemical Plant": 5,
    Phlebotomist: 5,
    "Chemical Tech": 5,
    Paramedic: 3,
    "Licensed Nurse": 5,
    "Home Caretaker": 5,
    "Nursing Assistant": 5,
    "Dental Assistant": 5,
    "Medical Admin": 5,
    "Dental Tech": 5,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 4,
    "Truck Driver": 2,
    "Cargo Agent": 4,
    "Food Service Manager": 5,
    "AV Technician": 5,
    "Video Editor": 5,
    Cook: 5,
    Hairdresser: 5,
    Manicurist: 5,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 5,
  },
  "I prefer working in jobs that keep me active and moving.": {
    "Farm Manager": 5,
    "Conservation Tech": 5,
    "Animal Caretaker": 5,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 5,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 3,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 3,
    Plumber: 3,
    "Sheet Metal": 4,
    "Highway Worker": 5,
    Painter: 4,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 5,
    Carpenter: 5,
    "Cement Mason": 5,
    Paver: 5,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 5,
    "HVAC Tech": 3,
    "Crane Operator": 4,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 3,
    Machinist: 3,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 2,
    Phlebotomist: 3,
    "Chemical Tech": 3,
    Paramedic: 4,
    "Licensed Nurse": 3,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 3,
    "Medical Admin": 2,
    "Dental Tech": 3,
    "Subway Operator": 2,
    "Machine Operator": 3,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 3,
    "AV Technician": 2,
    "Video Editor": 1,
    Cook: 4,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 4,
  },
  "I can think critically to devise effective strategies for problem-solving.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 4,
      "Animal Caretaker": 3,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 4,
      "Pest Control": 4,
      "Landscape Architect": 4,
      Boilermaker: 4,
      "Solar Installer": 4,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 4,
      "Commercial Diver": 4,
      "Recycling Coordinator": 4,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 3,
      "Highway Worker": 3,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 3,
      Carpenter: 4,
      "Cement Mason": 3,
      Paver: 3,
      Insulator: 3,
      Plasterer: 3,
      Roofer: 3,
      "HVAC Tech": 4,
      "Crane Operator": 4,
      "Bio Manufacturer": 4,
      "Metal Fabricator": 4,
      "Tool and Die Maker": 4,
      Machinist: 4,
      "Cabinet Maker": 4,
      Welder: 4,
      "Chemical Plant": 4,
      Phlebotomist: 3,
      "Chemical Tech": 4,
      Paramedic: 4,
      "Licensed Nurse": 4,
      "Home Caretaker": 3,
      "Nursing Assistant": 3,
      "Dental Assistant": 3,
      "Medical Admin": 3,
      "Dental Tech": 3,
      "Subway Operator": 3,
      "Machine Operator": 4,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 4,
      "Truck Driver": 3,
      "Cargo Agent": 3,
      "Food Service Manager": 4,
      "AV Technician": 4,
      "Video Editor": 4,
      Cook: 4,
      Hairdresser: 3,
      Manicurist: 3,
      "Auto Body": 4,
      "Appliance Repair": 4,
      Baker: 4,
    },
  "I appreciate the artistic aspects of my job and always strive for creativity.":
    {
      "Farm Manager": 3,
      "Conservation Tech": 3,
      "Animal Caretaker": 2,
      "Agricultural Inspector": 2,
      "Agricultural Operator": 2,
      "Greenhouse Manager": 3,
      "Pest Control": 2,
      "Landscape Architect": 5,
      Boilermaker: 2,
      "Solar Installer": 2,
      "Oil Operator": 1,
      "Electrical Power-Line": 2,
      "Wind Service": 2,
      "Commercial Diver": 3,
      "Recycling Coordinator": 3,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 2,
      Plumber: 2,
      "Sheet Metal": 3,
      "Highway Worker": 2,
      Painter: 5,
      "Tile Setter": 4,
      "Flooring Installer": 3,
      "Brick Mason": 4,
      Carpenter: 4,
      "Cement Mason": 3,
      Paver: 3,
      Insulator: 2,
      Plasterer: 3,
      Roofer: 2,
      "HVAC Tech": 2,
      "Crane Operator": 2,
      "Bio Manufacturer": 2,
      "Metal Fabricator": 3,
      "Tool and Die Maker": 3,
      Machinist: 2,
      "Cabinet Maker": 5,
      Welder: 3,
      "Chemical Plant": 1,
      Phlebotomist: 2,
      "Chemical Tech": 2,
      Paramedic: 2,
      "Licensed Nurse": 2,
      "Home Caretaker": 2,
      "Nursing Assistant": 2,
      "Dental Assistant": 2,
      "Medical Admin": 2,
      "Dental Tech": 3,
      "Subway Operator": 1,
      "Machine Operator": 2,
      "Aircraft Maintenance": 2,
      "Automotive Mechanic": 3,
      "Equipment Mechanic": 3,
      "Bike Mechanic": 3,
      "Truck Driver": 1,
      "Cargo Agent": 1,
      "Food Service Manager": 3,
      "AV Technician": 4,
      "Video Editor": 5,
      Cook: 5,
      Hairdresser: 5,
      Manicurist: 5,
      "Auto Body": 4,
      "Appliance Repair": 3,
      Baker: 5,
    },
  "I enjoy working with colors, textures, and patterns to create visually pleasing results.":
    {
      "Farm Manager": 3,
      "Conservation Tech": 3,
      "Animal Caretaker": 2,
      "Agricultural Inspector": 2,
      "Agricultural Operator": 2,
      "Greenhouse Manager": 3,
      "Pest Control": 2,
      "Landscape Architect": 5,
      Boilermaker: 2,
      "Solar Installer": 2,
      "Oil Operator": 1,
      "Electrical Power-Line": 2,
      "Wind Service": 2,
      "Commercial Diver": 3,
      "Recycling Coordinator": 3,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 2,
      Plumber: 2,
      "Sheet Metal": 3,
      "Highway Worker": 2,
      Painter: 5,
      "Tile Setter": 4,
      "Flooring Installer": 3,
      "Brick Mason": 4,
      Carpenter: 4,
      "Cement Mason": 3,
      Paver: 3,
      Insulator: 2,
      Plasterer: 3,
      Roofer: 2,
      "HVAC Tech": 2,
      "Crane Operator": 2,
      "Bio Manufacturer": 2,
      "Metal Fabricator": 3,
      "Tool and Die Maker": 3,
      Machinist: 2,
      "Cabinet Maker": 5,
      Welder: 3,
      "Chemical Plant": 1,
      Phlebotomist: 2,
      "Chemical Tech": 2,
      Paramedic: 2,
      "Licensed Nurse": 2,
      "Home Caretaker": 2,
      "Nursing Assistant": 2,
      "Dental Assistant": 2,
      "Medical Admin": 2,
      "Dental Tech": 3,
      "Subway Operator": 1,
      "Machine Operator": 2,
      "Aircraft Maintenance": 2,
      "Automotive Mechanic": 3,
      "Equipment Mechanic": 3,
      "Bike Mechanic": 3,
      "Truck Driver": 1,
      "Cargo Agent": 1,
      "Food Service Manager": 3,
      "AV Technician": 4,
      "Video Editor": 5,
      Cook: 5,
      Hairdresser: 5,
      Manicurist: 5,
      "Auto Body": 4,
      "Appliance Repair": 3,
      Baker: 5,
    },
  "I am comfortable standing for long periods of time.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 3,
    "Recycling Coordinator": 3,
    "Carpet Installer": 5,
    Drywaller: 5,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 5,
    Painter: 4,
    "Tile Setter": 5,
    "Flooring Installer": 5,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 4,
    "Crane Operator": 3,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 3,
    Phlebotomist: 3,
    "Chemical Tech": 3,
    Paramedic: 4,
    "Licensed Nurse": 3,
    "Home Caretaker": 3,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 3,
    "Dental Tech": 3,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 4,
    "Truck Driver": 2,
    "Cargo Agent": 3,
    "Food Service Manager": 4,
    "AV Technician": 3,
    "Video Editor": 2,
    Cook: 5,
    Hairdresser: 4,
    Manicurist: 4,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 4,
  },
  "I enjoy working in teams and collaborating with colleagues.": {
    "Farm Manager": 4,
    "Conservation Tech": 3,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 4,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 3,
    "Recycling Coordinator": 4,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 3,
    Plumber: 3,
    "Sheet Metal": 3,
    "Highway Worker": 3,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 4,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 3,
    "Crane Operator": 3,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 3,
    "Tool and Die Maker": 3,
    Machinist: 3,
    "Cabinet Maker": 3,
    Welder: 3,
    "Chemical Plant": 4,
    Phlebotomist: 3,
    "Chemical Tech": 4,
    Paramedic: 5,
    "Licensed Nurse": 4,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 4,
    "Dental Tech": 4,
    "Subway Operator": 3,
    "Machine Operator": 3,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 3,
    "Equipment Mechanic": 3,
    "Bike Mechanic": 3,
    "Truck Driver": 2,
    "Cargo Agent": 4,
    "Food Service Manager": 5,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 4,
    Hairdresser: 4,
    Manicurist: 4,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 4,
  },
  "I can easily lift heavy objects and perform physically demanding tasks.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 3,
    "Pest Control": 4,
    "Landscape Architect": 3,
    Boilermaker: 5,
    "Solar Installer": 4,
    "Oil Operator": 5,
    "Electrical Power-Line": 5,
    "Wind Service": 4,
    "Commercial Diver": 5,
    "Recycling Coordinator": 3,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 3,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 5,
    Painter: 3,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 5,
    Carpenter: 4,
    "Cement Mason": 5,
    Paver: 5,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 5,
    "HVAC Tech": 4,
    "Crane Operator": 5,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 3,
    "Cabinet Maker": 4,
    Welder: 5,
    "Chemical Plant": 3,
    Phlebotomist: 2,
    "Chemical Tech": 3,
    Paramedic: 4,
    "Licensed Nurse": 3,
    "Home Caretaker": 3,
    "Nursing Assistant": 3,
    "Dental Assistant": 2,
    "Medical Admin": 1,
    "Dental Tech": 2,
    "Subway Operator": 2,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 3,
    "Cargo Agent": 2,
    "Food Service Manager": 2,
    "AV Technician": 2,
    "Video Editor": 1,
    Cook: 3,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 4,
    "Appliance Repair": 3,
    Baker: 3,
  },
  "I can quickly notice if something is out of place or not done correctly.": {
    "Farm Manager": 3,
    "Conservation Tech": 3,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 3,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 4,
    Painter: 4,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 3,
    Phlebotomist: 3,
    "Chemical Tech": 3,
    Paramedic: 3,
    "Licensed Nurse": 3,
    "Home Caretaker": 3,
    "Nursing Assistant": 3,
    "Dental Assistant": 3,
    "Medical Admin": 3,
    "Dental Tech": 3,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 3,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 4,
    Hairdresser: 4,
    Manicurist: 4,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 4,
  },
  "I have no problem with tasks that require bending, kneeling, or climbing.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 4,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 3,
    Boilermaker: 4,
    "Solar Installer": 4,
    "Oil Operator": 3,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 3,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 4,
    Painter: 4,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 3,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 4,
    Welder: 4,
    "Chemical Plant": 3,
    Phlebotomist: 3,
    "Chemical Tech": 3,
    Paramedic: 4,
    "Licensed Nurse": 3,
    "Home Caretaker": 3,
    "Nursing Assistant": 3,
    "Dental Assistant": 2,
    "Medical Admin": 2,
    "Dental Tech": 2,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 4,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 3,
    "AV Technician": 3,
    "Video Editor": 2,
    Cook: 3,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 3,
  },
  "I am thorough when completing tasks and always double-check my work.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 5,
    "Agricultural Operator": 4,
    "Greenhouse Manager": 4,
    "Pest Control": 4,
    "Landscape Architect": 4,
    Boilermaker: 5,
    "Solar Installer": 4,
    "Oil Operator": 4,
    "Electrical Power-Line": 5,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 4,
    Drywaller: 4,
    Electrician: 5,
    Plumber: 5,
    "Sheet Metal": 5,
    "Highway Worker": 4,
    Painter: 4,
    "Tile Setter": 4,
    "Flooring Installer": 4,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 4,
    Roofer: 4,
    "HVAC Tech": 5,
    "Crane Operator": 4,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 5,
    "Tool and Die Maker": 5,
    Machinist: 5,
    "Cabinet Maker": 4,
    Welder: 5,
    "Chemical Plant": 4,
    Phlebotomist: 4,
    "Chemical Tech": 4,
    Paramedic: 4,
    "Licensed Nurse": 4,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 3,
    "Dental Tech": 4,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 5,
    "Automotive Mechanic": 5,
    "Equipment Mechanic": 5,
    "Bike Mechanic": 5,
    "Truck Driver": 3,
    "Cargo Agent": 3,
    "Food Service Manager": 4,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 4,
    Hairdresser: 4,
    Manicurist: 4,
    "Auto Body": 4,
    "Appliance Repair": 4,
    Baker: 4,
  },
  "I enjoy staying updated on the latest technological advancements in my field.":
    {
      "Farm Manager": 3,
      "Conservation Tech": 3,
      "Animal Caretaker": 2,
      "Agricultural Inspector": 3,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 3,
      "Pest Control": 3,
      "Landscape Architect": 3,
      Boilermaker: 3,
      "Solar Installer": 5,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 5,
      "Commercial Diver": 3,
      "Recycling Coordinator": 4,
      "Carpet Installer": 2,
      Drywaller: 2,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 4,
      "Highway Worker": 3,
      Painter: 2,
      "Tile Setter": 2,
      "Flooring Installer": 2,
      "Brick Mason": 2,
      Carpenter: 3,
      "Cement Mason": 2,
      Paver: 2,
      Insulator: 3,
      Plasterer: 2,
      Roofer: 2,
      "HVAC Tech": 4,
      "Crane Operator": 3,
      "Bio Manufacturer": 5,
      "Metal Fabricator": 3,
      "Tool and Die Maker": 3,
      Machinist: 4,
      "Cabinet Maker": 3,
      Welder: 3,
      "Chemical Plant": 4,
      Phlebotomist: 3,
      "Chemical Tech": 4,
      Paramedic: 4,
      "Licensed Nurse": 3,
      "Home Caretaker": 2,
      "Nursing Assistant": 2,
      "Dental Assistant": 3,
      "Medical Admin": 3,
      "Dental Tech": 4,
      "Subway Operator": 3,
      "Machine Operator": 4,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 3,
      "Cargo Agent": 3,
      "Food Service Manager": 3,
      "AV Technician": 5,
      "Video Editor": 5,
      Cook: 3,
      Hairdresser: 3,
      Manicurist: 2,
      "Auto Body": 4,
      "Appliance Repair": 4,
      Baker: 3,
    },
  "I have a strong sense of aesthetics and appreciate visually appealing designs.":
    {
      "Farm Manager": 2,
      "Conservation Tech": 3,
      "Animal Caretaker": 2,
      "Agricultural Inspector": 2,
      "Agricultural Operator": 2,
      "Greenhouse Manager": 3,
      "Pest Control": 1,
      "Landscape Architect": 5,
      Boilermaker: 2,
      "Solar Installer": 2,
      "Oil Operator": 1,
      "Electrical Power-Line": 1,
      "Wind Service": 2,
      "Commercial Diver": 2,
      "Recycling Coordinator": 2,
      "Carpet Installer": 4,
      Drywaller: 3,
      Electrician: 2,
      Plumber: 2,
      "Sheet Metal": 3,
      "Highway Worker": 2,
      Painter: 5,
      "Tile Setter": 5,
      "Flooring Installer": 4,
      "Brick Mason": 4,
      Carpenter: 4,
      "Cement Mason": 4,
      Paver: 4,
      Insulator: 2,
      Plasterer: 4,
      Roofer: 3,
      "HVAC Tech": 2,
      "Crane Operator": 2,
      "Bio Manufacturer": 2,
      "Metal Fabricator": 3,
      "Tool and Die Maker": 3,
      Machinist: 2,
      "Cabinet Maker": 5,
      Welder: 3,
      "Chemical Plant": 1,
      Phlebotomist: 1,
      "Chemical Tech": 1,
      Paramedic: 1,
      "Licensed Nurse": 1,
      "Home Caretaker": 1,
      "Nursing Assistant": 1,
      "Dental Assistant": 2,
      "Medical Admin": 1,
      "Dental Tech": 3,
      "Subway Operator": 1,
      "Machine Operator": 2,
      "Aircraft Maintenance": 2,
      "Automotive Mechanic": 3,
      "Equipment Mechanic": 2,
      "Bike Mechanic": 3,
      "Truck Driver": 1,
      "Cargo Agent": 1,
      "Food Service Manager": 4,
      "AV Technician": 4,
      "Video Editor": 5,
      Cook: 4,
      Hairdresser: 5,
      Manicurist: 5,
      "Auto Body": 4,
      "Appliance Repair": 2,
      Baker: 4,
    },
  "I have a strong understanding of how machines and mechanical systems work.":
    {
      "Farm Manager": 3,
      "Conservation Tech": 3,
      "Animal Caretaker": 2,
      "Agricultural Inspector": 3,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 2,
      "Pest Control": 2,
      "Landscape Architect": 2,
      Boilermaker: 4,
      "Solar Installer": 4,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 4,
      "Commercial Diver": 3,
      "Recycling Coordinator": 3,
      "Carpet Installer": 2,
      Drywaller: 2,
      Electrician: 5,
      Plumber: 5,
      "Sheet Metal": 4,
      "Highway Worker": 3,
      Painter: 2,
      "Tile Setter": 2,
      "Flooring Installer": 2,
      "Brick Mason": 2,
      Carpenter: 4,
      "Cement Mason": 2,
      Paver: 3,
      Insulator: 3,
      Plasterer: 2,
      Roofer: 3,
      "HVAC Tech": 5,
      "Crane Operator": 4,
      "Bio Manufacturer": 4,
      "Metal Fabricator": 5,
      "Tool and Die Maker": 5,
      Machinist: 5,
      "Cabinet Maker": 4,
      Welder: 5,
      "Chemical Plant": 4,
      Phlebotomist: 1,
      "Chemical Tech": 3,
      Paramedic: 2,
      "Licensed Nurse": 2,
      "Home Caretaker": 1,
      "Nursing Assistant": 1,
      "Dental Assistant": 1,
      "Medical Admin": 1,
      "Dental Tech": 2,
      "Subway Operator": 3,
      "Machine Operator": 5,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 5,
      "Equipment Mechanic": 5,
      "Bike Mechanic": 4,
      "Truck Driver": 3,
      "Cargo Agent": 2,
      "Food Service Manager": 1,
      "AV Technician": 3,
      "Video Editor": 2,
      Cook: 1,
      Hairdresser: 1,
      Manicurist: 1,
      "Auto Body": 4,
      "Appliance Repair": 4,
      Baker: 1,
    },
  "I am able to adapt my communication style to different situations and people.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 4,
      "Animal Caretaker": 3,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 4,
      "Pest Control": 3,
      "Landscape Architect": 4,
      Boilermaker: 3,
      "Solar Installer": 3,
      "Oil Operator": 3,
      "Electrical Power-Line": 3,
      "Wind Service": 3,
      "Commercial Diver": 3,
      "Recycling Coordinator": 4,
      "Carpet Installer": 2,
      Drywaller: 2,
      Electrician: 3,
      Plumber: 3,
      "Sheet Metal": 3,
      "Highway Worker": 2,
      Painter: 2,
      "Tile Setter": 2,
      "Flooring Installer": 2,
      "Brick Mason": 2,
      Carpenter: 3,
      "Cement Mason": 2,
      Paver: 2,
      Insulator: 2,
      Plasterer: 2,
      Roofer: 2,
      "HVAC Tech": 3,
      "Crane Operator": 3,
      "Bio Manufacturer": 3,
      "Metal Fabricator": 3,
      "Tool and Die Maker": 2,
      Machinist: 2,
      "Cabinet Maker": 3,
      Welder: 2,
      "Chemical Plant": 3,
      Phlebotomist: 4,
      "Chemical Tech": 4,
      Paramedic: 5,
      "Licensed Nurse": 5,
      "Home Caretaker": 4,
      "Nursing Assistant": 4,
      "Dental Assistant": 4,
      "Medical Admin": 4,
      "Dental Tech": 3,
      "Subway Operator": 3,
      "Machine Operator": 2,
      "Aircraft Maintenance": 3,
      "Automotive Mechanic": 3,
      "Equipment Mechanic": 3,
      "Bike Mechanic": 3,
      "Truck Driver": 3,
      "Cargo Agent": 4,
      "Food Service Manager": 5,
      "AV Technician": 3,
      "Video Editor": 3,
      Cook: 3,
      Hairdresser: 5,
      Manicurist: 5,
      "Auto Body": 3,
      "Appliance Repair": 3,
      Baker: 3,
    },
  "I can effectively manage conflicts and find common ground in disagreements.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 4,
      "Animal Caretaker": 3,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 4,
      "Pest Control": 3,
      "Landscape Architect": 4,
      Boilermaker: 3,
      "Solar Installer": 3,
      "Oil Operator": 3,
      "Electrical Power-Line": 3,
      "Wind Service": 3,
      "Commercial Diver": 3,
      "Recycling Coordinator": 4,
      "Carpet Installer": 2,
      Drywaller: 2,
      Electrician: 3,
      Plumber: 3,
      "Sheet Metal": 3,
      "Highway Worker": 2,
      Painter: 2,
      "Tile Setter": 2,
      "Flooring Installer": 2,
      "Brick Mason": 2,
      Carpenter: 3,
      "Cement Mason": 2,
      Paver: 2,
      Insulator: 2,
      Plasterer: 2,
      Roofer: 2,
      "HVAC Tech": 3,
      "Crane Operator": 3,
      "Bio Manufacturer": 3,
      "Metal Fabricator": 3,
      "Tool and Die Maker": 2,
      Machinist: 2,
      "Cabinet Maker": 3,
      Welder: 2,
      "Chemical Plant": 3,
      Phlebotomist: 4,
      "Chemical Tech": 4,
      Paramedic: 5,
      "Licensed Nurse": 5,
      "Home Caretaker": 4,
      "Nursing Assistant": 4,
      "Dental Assistant": 4,
      "Medical Admin": 4,
      "Dental Tech": 3,
      "Subway Operator": 3,
      "Machine Operator": 2,
      "Aircraft Maintenance": 3,
      "Automotive Mechanic": 3,
      "Equipment Mechanic": 3,
      "Bike Mechanic": 3,
      "Truck Driver": 3,
      "Cargo Agent": 4,
      "Food Service Manager": 5,
      "AV Technician": 3,
      "Video Editor": 3,
      Cook: 3,
      Hairdresser: 5,
      Manicurist: 5,
      "Auto Body": 3,
      "Appliance Repair": 3,
      Baker: 3,
    },
  "I can easily adjust my schedule to accommodate unexpected changes or urgent tasks.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 3,
      "Animal Caretaker": 3,
      "Agricultural Inspector": 3,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 3,
      "Pest Control": 3,
      "Landscape Architect": 3,
      Boilermaker: 3,
      "Solar Installer": 3,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 4,
      "Commercial Diver": 4,
      "Recycling Coordinator": 3,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 3,
      "Highway Worker": 3,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 3,
      Carpenter: 3,
      "Cement Mason": 3,
      Paver: 3,
      Insulator: 3,
      Plasterer: 3,
      Roofer: 3,
      "HVAC Tech": 4,
      "Crane Operator": 4,
      "Bio Manufacturer": 3,
      "Metal Fabricator": 3,
      "Tool and Die Maker": 3,
      Machinist: 3,
      "Cabinet Maker": 3,
      Welder: 3,
      "Chemical Plant": 4,
      Phlebotomist: 3,
      "Chemical Tech": 3,
      Paramedic: 5,
      "Licensed Nurse": 4,
      "Home Caretaker": 3,
      "Nursing Assistant": 4,
      "Dental Assistant": 3,
      "Medical Admin": 3,
      "Dental Tech": 3,
      "Subway Operator": 3,
      "Machine Operator": 3,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 4,
      "Cargo Agent": 3,
      "Food Service Manager": 4,
      "AV Technician": 3,
      "Video Editor": 3,
      Cook: 4,
      Hairdresser: 3,
      Manicurist: 3,
      "Auto Body": 4,
      "Appliance Repair": 4,
      Baker: 3,
    },
  "I can think outside the box and come up with innovative solutions.": {
    "Farm Manager": 3,
    "Conservation Tech": 3,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 2,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 3,
    "Solar Installer": 4,
    "Oil Operator": 3,
    "Electrical Power-Line": 3,
    "Wind Service": 4,
    "Commercial Diver": 3,
    "Recycling Coordinator": 4,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 3,
    Plumber: 3,
    "Sheet Metal": 3,
    "Highway Worker": 2,
    Painter: 3,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 2,
    Carpenter: 3,
    "Cement Mason": 2,
    Paver: 2,
    Insulator: 2,
    Plasterer: 2,
    Roofer: 2,
    "HVAC Tech": 3,
    "Crane Operator": 2,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 3,
    "Tool and Die Maker": 3,
    Machinist: 3,
    "Cabinet Maker": 3,
    Welder: 3,
    "Chemical Plant": 4,
    Phlebotomist: 2,
    "Chemical Tech": 3,
    Paramedic: 3,
    "Licensed Nurse": 2,
    "Home Caretaker": 2,
    "Nursing Assistant": 2,
    "Dental Assistant": 2,
    "Medical Admin": 2,
    "Dental Tech": 2,
    "Subway Operator": 2,
    "Machine Operator": 2,
    "Aircraft Maintenance": 3,
    "Automotive Mechanic": 3,
    "Equipment Mechanic": 3,
    "Bike Mechanic": 2,
    "Truck Driver": 2,
    "Cargo Agent": 2,
    "Food Service Manager": 3,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 3,
    Hairdresser: 3,
    Manicurist: 2,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 3,
  },
  "I am comfortable learning and working with complex technical systems.": {
    "Farm Manager": 3,
    "Conservation Tech": 3,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 3,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 3,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 4,
    "Solar Installer": 5,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 5,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 2,
    Painter: 2,
    "Tile Setter": 2,
    "Flooring Installer": 2,
    "Brick Mason": 2,
    Carpenter: 3,
    "Cement Mason": 2,
    Paver: 2,
    Insulator: 3,
    Plasterer: 2,
    Roofer: 2,
    "HVAC Tech": 4,
    "Crane Operator": 3,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 3,
    Welder: 4,
    "Chemical Plant": 5,
    Phlebotomist: 2,
    "Chemical Tech": 4,
    Paramedic: 3,
    "Licensed Nurse": 2,
    "Home Caretaker": 2,
    "Nursing Assistant": 2,
    "Dental Assistant": 2,
    "Medical Admin": 2,
    "Dental Tech": 2,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 2,
    "Cargo Agent": 2,
    "Food Service Manager": 2,
    "AV Technician": 5,
    "Video Editor": 4,
    Cook: 2,
    Hairdresser: 2,
    Manicurist: 2,
    "Auto Body": 3,
    "Appliance Repair": 4,
    Baker: 2,
  },
  "I can easily communicate my thoughts and ideas to others.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 4,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 3,
    "Solar Installer": 3,
    "Oil Operator": 3,
    "Electrical Power-Line": 3,
    "Wind Service": 3,
    "Commercial Diver": 3,
    "Recycling Coordinator": 4,
    "Carpet Installer": 2,
    Drywaller: 2,
    Electrician: 3,
    Plumber: 3,
    "Sheet Metal": 3,
    "Highway Worker": 3,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 4,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 3,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 4,
    "Metal Fabricator": 3,
    "Tool and Die Maker": 3,
    Machinist: 3,
    "Cabinet Maker": 3,
    Welder: 3,
    "Chemical Plant": 4,
    Phlebotomist: 4,
    "Chemical Tech": 4,
    Paramedic: 5,
    "Licensed Nurse": 4,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 4,
    "Dental Tech": 4,
    "Subway Operator": 3,
    "Machine Operator": 3,
    "Aircraft Maintenance": 3,
    "Automotive Mechanic": 3,
    "Equipment Mechanic": 3,
    "Bike Mechanic": 3,
    "Truck Driver": 3,
    "Cargo Agent": 4,
    "Food Service Manager": 5,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 3,
    Hairdresser: 5,
    Manicurist: 5,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 3,
  },
  "I am able to juggle multiple responsibilities without compromising the quality of my work.":
    {
      "Farm Manager": 4,
      "Conservation Tech": 4,
      "Animal Caretaker": 3,
      "Agricultural Inspector": 4,
      "Agricultural Operator": 3,
      "Greenhouse Manager": 4,
      "Pest Control": 3,
      "Landscape Architect": 4,
      Boilermaker: 3,
      "Solar Installer": 3,
      "Oil Operator": 4,
      "Electrical Power-Line": 4,
      "Wind Service": 4,
      "Commercial Diver": 4,
      "Recycling Coordinator": 4,
      "Carpet Installer": 3,
      Drywaller: 3,
      Electrician: 4,
      Plumber: 4,
      "Sheet Metal": 4,
      "Highway Worker": 3,
      Painter: 3,
      "Tile Setter": 3,
      "Flooring Installer": 3,
      "Brick Mason": 4,
      Carpenter: 4,
      "Cement Mason": 4,
      Paver: 4,
      Insulator: 4,
      Plasterer: 3,
      Roofer: 3,
      "HVAC Tech": 4,
      "Crane Operator": 4,
      "Bio Manufacturer": 5,
      "Metal Fabricator": 4,
      "Tool and Die Maker": 4,
      Machinist: 4,
      "Cabinet Maker": 3,
      Welder: 3,
      "Chemical Plant": 5,
      Phlebotomist: 4,
      "Chemical Tech": 4,
      Paramedic: 5,
      "Licensed Nurse": 4,
      "Home Caretaker": 4,
      "Nursing Assistant": 4,
      "Dental Assistant": 4,
      "Medical Admin": 4,
      "Dental Tech": 4,
      "Subway Operator": 3,
      "Machine Operator": 4,
      "Aircraft Maintenance": 4,
      "Automotive Mechanic": 4,
      "Equipment Mechanic": 4,
      "Bike Mechanic": 3,
      "Truck Driver": 3,
      "Cargo Agent": 4,
      "Food Service Manager": 5,
      "AV Technician": 4,
      "Video Editor": 4,
      Cook: 3,
      Hairdresser: 3,
      Manicurist: 3,
      "Auto Body": 3,
      "Appliance Repair": 3,
      Baker: 3,
    },
  "I am comfortable interacting with clients and customers.": {
    "Farm Manager": 4,
    "Conservation Tech": 4,
    "Animal Caretaker": 3,
    "Agricultural Inspector": 4,
    "Agricultural Operator": 3,
    "Greenhouse Manager": 4,
    "Pest Control": 3,
    "Landscape Architect": 4,
    Boilermaker: 3,
    "Solar Installer": 3,
    "Oil Operator": 4,
    "Electrical Power-Line": 4,
    "Wind Service": 4,
    "Commercial Diver": 4,
    "Recycling Coordinator": 4,
    "Carpet Installer": 3,
    Drywaller: 3,
    Electrician: 4,
    Plumber: 4,
    "Sheet Metal": 4,
    "Highway Worker": 3,
    Painter: 3,
    "Tile Setter": 3,
    "Flooring Installer": 3,
    "Brick Mason": 4,
    Carpenter: 4,
    "Cement Mason": 4,
    Paver: 4,
    Insulator: 4,
    Plasterer: 3,
    Roofer: 3,
    "HVAC Tech": 4,
    "Crane Operator": 4,
    "Bio Manufacturer": 5,
    "Metal Fabricator": 4,
    "Tool and Die Maker": 4,
    Machinist: 4,
    "Cabinet Maker": 3,
    Welder: 3,
    "Chemical Plant": 5,
    Phlebotomist: 4,
    "Chemical Tech": 4,
    Paramedic: 5,
    "Licensed Nurse": 4,
    "Home Caretaker": 4,
    "Nursing Assistant": 4,
    "Dental Assistant": 4,
    "Medical Admin": 4,
    "Dental Tech": 4,
    "Subway Operator": 3,
    "Machine Operator": 4,
    "Aircraft Maintenance": 4,
    "Automotive Mechanic": 4,
    "Equipment Mechanic": 4,
    "Bike Mechanic": 3,
    "Truck Driver": 3,
    "Cargo Agent": 4,
    "Food Service Manager": 5,
    "AV Technician": 4,
    "Video Editor": 4,
    Cook: 3,
    Hairdresser: 3,
    Manicurist: 3,
    "Auto Body": 3,
    "Appliance Repair": 3,
    Baker: 3,
  },
  "I enjoy expressing myself creatively through my work.": {
    "Farm Manager": 3,
    "Conservation Tech": 2,
    "Animal Caretaker": 2,
    "Agricultural Inspector": 1,
    "Agricultural Operator": 1,
    "Greenhouse Manager": 3,
    "Pest Control": 1,
    "Landscape Architect": 4,
    Boilermaker: 2,
    "Solar Installer": 2,
    "Oil Operator": 1,
    "Electrical Power-Line": 1,
    "Wind Service": 2,
    "Commercial Diver": 1,
    "Recycling Coordinator": 2,
    "Carpet Installer": 3,
    Drywaller: 2,
    Electrician: 2,
    Plumber: 2,
    "Sheet Metal": 2,
    "Highway Worker": 1,
    Painter: 4,
    "Tile Setter": 4,
    "Flooring Installer": 3,
    "Brick Mason": 3,
    Carpenter: 4,
    "Cement Mason": 3,
    Paver: 3,
    Insulator: 2,
    Plasterer: 3,
    Roofer: 2,
    "HVAC Tech": 2,
    "Crane Operator": 1,
    "Bio Manufacturer": 1,
    "Metal Fabricator": 3,
    "Tool and Die Maker": 3,
    Machinist: 2,
    "Cabinet Maker": 4,
    Welder: 3,
    "Chemical Plant": 1,
    Phlebotomist: 1,
    "Chemical Tech": 1,
    Paramedic: 1,
    "Licensed Nurse": 1,
    "Home Caretaker": 1,
    "Nursing Assistant": 1,
    "Dental Assistant": 1,
    "Medical Admin": 1,
    "Dental Tech": 2,
    "Subway Operator": 1,
    "Machine Operator": 1,
    "Aircraft Maintenance": 1,
    "Automotive Mechanic": 2,
    "Equipment Mechanic": 2,
    "Bike Mechanic": 2,
    "Truck Driver": 1,
    "Cargo Agent": 1,
    "Food Service Manager": 3,
    "AV Technician": 3,
    "Video Editor": 4,
    Cook: 4,
    Hairdresser: 5,
    Manicurist: 4,
    "Auto Body": 3,
    "Appliance Repair": 2,
    Baker: 5,
  },
};
